export enum ScheduleAction {
  ENABLE = 'ENABLE',
  PAUSE = 'PAUSE',
  ADJUST_BID = 'ADJUST_BID',
}

export enum ScheduleStatus {
  QUEUED = 'QUEUED',
  RUNNING = 'RUNNING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
  SCHEDULED = 'SCHEDULED',
  PENDING = 'PENDING'
}